name: SvxLink CI

# Spouštění workflow při push nebo pull requestu na větev main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Definice úloh (jobs)
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Stažení zdrojového kódu z repozitáře
      - name: Checkout code
        uses: actions/checkout@v4

      # Instalace závislostí potřebných pro SvxLink
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            libsigc++-2.0-dev \
            libgsm1-dev \
            libpopt-dev \
            tcl-dev \
            libgcrypt20-dev \
            libspeex-dev \
            libasound2-dev \
            libopus-dev \
            qt5-default \
            libvorbis-dev \
            libcurl4-openssl-dev \
            libssl-dev

      # Vytvoření build adresáře a konfigurace pomocí CMake
      - name: Configure
        run: |
          mkdir build
          cd build
          cmake ..

      # Kompilace projektu
      - name: Build
        run: |
          cd build
          make -j$(nproc)

      # Spuštění testů (pokud jsou k dispozici)
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure

      # Volitelný krok: Archivace sestavených binárek jako artefakty
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: svxlink-binaries
          path: build/src/
          
      # Publikace na GitHub Releases (pouze při tagu)
  #    - name: Create Release
  #     if: startsWith(github.ref, 'refs/tags/')
  #     uses: actions/create-release@v1
  #      env:
  #        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #      with:
  #        tag_name: ${{ github.ref }}
  #        release_name: Release ${{ github.ref }}
  #        draft: false
  #        prerelease: false
