name: SvxLink CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            libsigc++-2.0-dev \
            libgsm1-dev \
            libpopt-dev \
            tcl-dev \
            libgcrypt20-dev \
            libspeex-dev \
            libasound2-dev \
            libopus-dev \
            qtbase5-dev \
            qtmultimedia5-dev \
            libvorbis-dev \
            libcurl4-openssl-dev \
            libssl-dev

      - name: Configure
        run: |
          mkdir -p src/build
          cd src/build
          cmake ..

      - name: Build
        run: |
          cd src/build
          make -j$(nproc)

      - name: Run tests
        continue-on-error: true # Testy mohou být volitelné, pokud nejsou plně implementovány
        run: |
          cd src/build
          ctest --output-on-failure

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: svxlink-binaries
          path: src/build/src/
